language: python
python:
  - 3.6
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov
# command to run tests
script:
  - py.test --cov-report=term --cov=amity --cov=models --cov=../dojomanager
#  - coverage run --source=amity,models,tests test
after_success:
  - coveralls